### ISSUE TITLE
ImportError: module 'app' has no attribute 'secure'

### ISSUE THREAD

**Issue by jili3221058001** [Marticles/BookCrossing-website#1]
- 'app' found in 'K:\\BookCrossing-website-master\\app\\__init__.py'.
- 'app.secure' not found.

Original exception:

ImportError: module 'app' has no attribute 'secure'

def create_app():
    app = Flask(__name__)
    app.config.from_object('app.secure')
    app.config.from_object('app.setting')
    register_blueprint(app)

**Comment by Marticles** [comment]
Sorry,I have removed 'secure.py'.It looks like this:

`DEBUG` = False
SQLALCHEMY_DATABASE_URI = 'mysql+cymysql://username:password@localhost:3306/bookcrossing'
SECRET_KEY = 'A random string'

MAIL_SERVER = 'Email server'
MAIL_PORT = 25
MAIL_USE_SSL = True
MAIL_USE_TSL = False
MAIL_USERNAME = 'xxx@xxx.xxx'
MAIL_PASSWORD = 'your password'
MAIL_SENDER = 'XXXXXX'

**Comment by jili3221058001** [comment]
1、在以下目录加上以上的内容，就可以了
      app/secure.py 
2、需要在mysql数据库先，新建一个database，否则启动不了
      create database bookcrossing;

**Comment by Marticles** [comment]
解决就OK了 ：）
